[package]
name = "deploy_scripts"
version = "0.0.1"

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["jediswap_v2_core::jediswap_v2_pool::JediSwapV2Pool", "jediswap_v2_core::jediswap_v2_factory::JediSwapV2Factory"]

[dependencies]
starknet = "2.6.3"
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.20.1" }
jediswap_v2_core = { path = "../" }