[package]
name = "deploy_scripts"
version = "0.0.1"

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.3.1"
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.11.0" }
jediswap_v2_core = { path = "../" }